### ISSUE TITLE
StateManagement breaks existing non-interactive build with disabled secrets

### ISSUE THREAD

**Issue by AieatAssam** [prom3theu5/aspirational-manifests#183]
### 🔥 Bug Description
Since addition of state management support, non-interactive build as part of CI is failing with FileNotFound for aspirate-state.json.
--disable-state parameter is rejected by generate command

Issue occurs with version **0.7.0-preview**. Last working version is **0.6.10-preview**

### 🔍 Steps to Reproduce the Bug
1. In existing aspirate project, execute non interactive build:
aspirate generate --non-interactive --image-pull-policy Always --disable-secrets --include-dashboard false
2. Error is produced when loading state:
```
── Handling Aspirate State ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Unhandled exception: System.IO.FileNotFoundException: Could not find file '<SNIPPED>.AppHost\aspirate-state.json'.
File name: '<SNIPPED>.AppHost\aspirate-state.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at Aspirate.Services.Implementations.StateService.RestoreState(StateManagementOptions options, String stateFile, Boolean shouldUseAllPreviousStateValues) in /home/runner/work/aspirational-manifests/aspirational-manifests/src/Aspirate.Services/Implementations/StateService.cs:line 75
   at Aspirate.Services.Implementations.StateService.RestoreState(StateManagementOptions options) in /home/runner/work/aspirational-manifests/aspirational-manifests/src/Aspirate.Services/Implementations/StateService.cs:line 43
   at Aspirate.Commands.Commands.BaseCommand`2.ConstructCommand(TOptions options, IServiceCollection services) in /home/runner/work/aspirational-manifests/aspirational-manifests/src/Aspirate.Commands/Commands/BaseCommand.cs:line 36
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
3. Trying to pass --disable-state parameter results in error:
`Unrecognized command or argument '--disable-state'.`

### 🧯 Possible Solution
Update state management to verify state file presence prior to trying to load it

**Comment by prom3theu5** [comment]
Gimme an hour I'll take a look cheers

**Comment by AieatAssam** [comment]
> Gimme an hour I'll take a look cheers

Thank you. I'll pin the build to 0.6.10 for now, so take your time. Awesome tool, by the way, and very handy for CD of dev pipeline
